App/App/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('TeaYardApp.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include('debug_toolbar.urls')),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/TeaYardApp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('category/<int:category_id>/', get_category, name='category'),
    path('products/<int:products_id>/', view_products, name='view_products'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

App/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         cart_remove,
         name='cart_remove'),
]

App/TeaYardApp/models.py
from django.db import models
from django.urls import reverse


class Products(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    photo = models.ImageField(upload_to='photos/%Y/%M/%D/', blank=True)
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)

    def get_absolute_url(self):
        return reverse('view_products', kwargs={"products_id": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['category']


class Category(models.Model):
    title = models.CharField(max_length=150, db_index=True, verbose_name='Категория')

    def get_absolute_url(self):
        return reverse('category', kwargs={"category_id": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']

App/cart/models.py
from django.db import models

# Create your models here.

App/TeaYardApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Имя пользователя', widget=forms.TextInput(
            attrs={'class': 'form-control', 'autofocus': 'off'}
        )
    )
    password = forms.CharField(
        label='Пароль', widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'autofocus': 'off'}
        )
    )


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(
        label='Имя пользователя', max_length=50, help_text='Максимум 50 символов', widget=forms.TextInput(
            attrs={'class': 'form-control', 'autofocus': 'off'}
        )
    )
    password1 = forms.CharField(
        label='Пароль', widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'autofocus': 'off'}
        )
    )
    password2 = forms.CharField(
        label='Подтверждение пароля', widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'autofocus': 'off'}
        )
    )
    email = forms.EmailField(
        label='E-mail', widget=forms.EmailInput(
            attrs={'class': 'form-control', 'autofocus': 'off'}
        )
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

App/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(25, 100 + 1, 25)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label='Вес',
    )
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

App/TeaYardApp/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, logout

from cart.forms import CartAddProductForm
from .forms import UserRegisterForm, UserLoginForm

from .models import *


def index(request):
    products = Products.objects.filter(available=True)

    paginator = Paginator(products, 30)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'TeaYardApp/index.html',
                  {'products': products, 'page_obj': page_obj})


def get_category(request, category_id):
    products = Products.objects.filter(category_id=category_id)
    category = Category.objects.get(pk=category_id)

    paginator = Paginator(products, 30)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'TeaYardApp/category.html',
                  {'products': products, 'category': category, 'page_obj': page_obj})


def view_products(request, products_id):
    products_item = get_object_or_404(Products, id=products_id)
    cart_product_form = CartAddProductForm()
    return render(request, 'TeaYardApp/view_products.html',
                  {'products_item': products_item, 'cart_product_form': cart_product_form})


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Вы успешно зарегестрировались')
            return redirect('home')
        else:
            messages.error(request, 'Ошибка регистрации')
    else:
        form = UserRegisterForm()
    return render(request, 'TeaYardApp/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = UserLoginForm()
    return render(request, 'TeaYardApp/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('login')

App/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from TeaYardApp.models import Products
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'Cart/detail.html', {'cart': cart})

App/templates/Cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Корзина покупок
{% endblock %}

{% block content %}
<h1>Корзина покупок</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Картинка</th>
        <th>Товар</th>
        <th>Обновить кол-во</th>
        <th>Удалить</th>
        <th>Кол-во</th>
        <th>Цена за шт</th>
        <th>Общая стоимость</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'PDF/no_image.png' %}{% endif %}">
            </a>
        </td>
        <td>{{ product.name }}</td>
        <td>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
            </form>
        </td>
        <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
        <td>
            {{ item.quantity }}
        </td>
        <td class="num">{{ item.price }}</td>
        <td class="num">{{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'home' %}" class="button light">В магазин</a>
    <a href="#" class="button">Оформить заказ</a>
</p>
{% endblock %}

App/templates/TeaYardApp/category.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ block.super }}
{% endblock %}


{% block content %}
{% for item in products %}
<div class="col">
    <div class="card" style="width: 18rem;">
        {% if item.photo %}
        <a href="{{ item.get_absolute_url }}"><img src="{{ item.photo.url }}" class="card-img-top" width="100%"
                                                   height="260"></a>
        {% else %}
        <a href="{{ item.get_absolute_url }}"><img class="card-img-top" href="{% static 'PDF/no_image.png' %}"
                                                   width="100%" height="260"/></a>
        {% endif %}
        <div class="card-body">
            <a href="{{ item.get_absolute_url }}" class="view_products" style="margin-bottom:20px"><h5
                    class="card-title">{{ item.title }}</h5></a>
            <div class="d-flex justify-content-between align-items-center">
                {% if item.price == 7 or item.price == 6 %}
                <h6 class="text-muted">{{ item.price }} руб/50г</h6>
                {% else %}
                <h6 class="text-muted">{{ item.price }}0 руб/50г</h6>
                {% endif %}
                <a class="cart_link" href="{{ item.get_absolute_url }}">
                    <button type="submit" class="btn btn-sm btn-outline-secondary">Подробнее</button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

App/templates/TeaYardApp/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ block.super }}
{% endblock %}


{% block content %}
{% for item in products %}
<div class="col" style="">
    <div class="card" style="width: 18rem;">
        {% if item.photo %}
        <a href="{{ item.get_absolute_url }}"><img src="{{ item.photo.url }}" class="card-img-top" width="100%"
                                                   height="260"></a>
        {% else %}
        <a href="{{ item.get_absolute_url }}"><img class="card-img-top" href="{% static 'PDF/no_image.png' %}"
                                                   width="100%" height="260"/></a>
        {% endif %}
        <div class="card-body">
            <a href="{{ item.get_absolute_url }}" class="view_products" style="margin-bottom:20px"><h5
                    class="card-title">{{ item.title }}</h5></a>
            <div class="d-flex justify-content-between align-items-center">
                <h6 class="text-muted">{{ item.price }} руб/50г</h6>
                <a class="cart_link" href="{{ item.get_absolute_url }}">
                    <button type="submit" class="btn btn-sm btn-outline-secondary">Подробнее</button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

App/templates/TeaYardApp/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Авторизация :: {{ block.super }}
{% endblock %}


{% block content %}
<form method="post" style="margin:0 auto;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Авторизация</button>
</form>
{% endblock %}

App/templates/TeaYardApp/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Регистрация :: {{ block.super }}
{% endblock %}


{% block content %}

<form method="post" style="margin:0 auto;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Регистрация</button>
</form>
{% endblock %}

App/templates/TeaYardApp/view_products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ block.super }}
{% endblock %}

{% block content %}
<div class="col" style="margin:0 auto;">
    <div class="card" style="width: 25rem;">
        {% if products_item.photo %}
        <img src="{{ products_item.photo.url }}" class="card-img-top" width="100%"
             height="260">
        {% else %}
        <img class="card-img-top" href="{% static 'PDF/no_image.png' %}"
             width="100%" height="260"/>
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ products_item.title }}</h5>
            <p class="card-text">{{ products_item.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
                {% if products_item.price|length==1 %}
                <h6 class="text-muted">{{ products_item.price }} руб/50г</h6>
                {% else %}
                <h6 class="text-muted">{{ products_item.price }}0 руб/50г</h6>
                {% endif %}
<!--                <form action="{% url 'cart:cart_add' products_item.id %}" method="post">-->
<!--                    {{ cart_product_form }}-->
<!--                    {% if request.user.is_authenticated %}-->
<!--                    <button type="submit" class="btn btn-secondary">В корзину</button>-->
<!--                    {% else %}-->
<!--                    <button type="button" class="btn btn-danger" data-bs-toggle="popover"-->
<!--                            data-bs-content="Зарегестрируйтесь чтобы класти товары в корзину и делать заказы">В-->
<!--                        корзину-->
<!--                    </button>-->
<!--                    {% endif %}-->
<!--                    {% csrf_token %}-->
<!--                </form>-->
            </div>
        </div>
    </div>
</div>
{% endblock %}

App/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/album/">
    <title>{% block title %}Чайный дворик{% endblock %}</title>
    <style>
* {
    box-sizing: border-box;
}

.card {
    float: left;
    width: 33.33%;
}

.row:after {
    content: "";
    display: table;
    clear: both;
}

@media screen  {
    .card {
        width: 100%;
    }
}



    </style>
</head>
<body>

<!--{% if messages %}-->

<!--{% for message in messages %}-->

<!--{% if message.tags == 'error' %}-->
<!--<div class="alert alert-danger" role="alert">-->
<!--    {{ message }}-->
<!--</div>-->
<!--{% else %}-->
<!--<div class="alert alert-{{ message.tags }}" role="alert">-->
<!--    A simple primary alert—check it out!-->
<!--</div>-->
<!--{% endif %}-->

<!--{% endfor %}-->

<!--{% endif %}-->

{% include 'inc/_nav.html' %}


<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% block content %}CONTENT{% endblock %}

        </div>
    </div>
</div>


{% include 'inc/_downbar.html' %}


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
        integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
        crossorigin="anonymous"></script>
</body>
</html>

App/templates/inc/_downbar.html
{% block downbar %}
<footer class="text-muted py-5">
    {% for item in page_obj.paginator.page_range %}
    <nav aria-label="Page navigation example" style="margin-top:18px">
        <ul class="pagination justify-content-center">
            <li class="page-item"><a class="page-link" href="?page={{ item.has_previous }}">Предыдущая</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ item }}">{{ item }}</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ item.has_next }}">Следущая</a></li>
        </ul>
    </nav>
    {% endfor %}
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Вернуться на верх</a>
        </p>
    </div>
</footer>
{% endblock %}

App/templates/inc/_nav.html
{% load tea_tags %}
{% get_list_categories as categories %}
<nav class="navbar bg-light">
    <div class="container-fluid">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Главная</a>
            </li>
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="{{ cart.clear }}">jx</a>-->
<!--            </li>-->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                   aria-expanded="false">Контакты</a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="nav-link active" aria-current="page" href="#">Наш VK</a>
                        <a class="nav-link active" aria-current="page" href="#">Наш Instagram</a>
                        <a class="nav-link active" aria-current="page" href="#">Наш Telegram</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                   aria-expanded="false">Каталог</a>
                <ul class="dropdown-menu">
                    <li>
                        {% for item in categories %}
                        <a href="{% url 'category' item.pk %}"
                           class="nav-link">{{ item.title }}</a>
                        {% endfor %}
                    </li>
                </ul>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Выход</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{% url 'register' %}" class="nav-link">Регистрация</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'login' %}" class="nav-link">Авторизация</a>
            </li>
            {% endif %}
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="{% url 'cart:cart_detail' %}">Корзина</a>-->
<!--            </li>-->
        </ul>

        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
                aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
             aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Чайный дворик</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Выход</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'register' %}" class="nav-link">Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link">Авторизация</a>
                    </li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                           aria-expanded="false">Контакты</a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="nav-link active" aria-current="page" href="#">Наш VK</a>
                                <a class="nav-link active" aria-current="page" href="#">Наш Instagram</a>
                                <a class="nav-link active" aria-current="page" href="#">Наш Telegram</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                           aria-expanded="false">Каталог</a>
                        <ul class="dropdown-menu">
                            <li>{% for item in categories %}
                                <a href="{% url 'category' item.pk %}"
                                   class="nav-link">{{ item.title }}</a>
                                {% endfor %}
                            </li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
</nav>


<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Чайный дворик</h1>
            <p class="lead text-muted">Something short and leading about the collection below—its contents, the
                creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it
                entirely.</p>

            <div>
                {% for item in categories %}
                <a href="{% url 'category' item.pk %}"
                   class="btn btn-primary my-2" style="width:100px;">{{ item.title }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

App/templates/inc/_sidebar.html
<div class="btn-group-vertical">
    <ol class="list-group list-group-numbered">
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold">Subheading</div>
                Content for list item
            </div>
            <span class="badge bg-primary rounded-pill">14</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold">Subheading</div>
                Content for list item
            </div>
            <span class="badge bg-primary rounded-pill">14</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold">Subheading</div>
                Content for list item
            </div>
            <span class="badge bg-primary rounded-pill">14</span>
        </li>
    </ol>
</div>